@extends('layouts.master')
@section('title')
    Billing #{{ $billing->billing_period }} - {{ $billing->tenant->name }}
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            <a href="{{ route('admin.tenant-billings.index') }}">Billings</a>
        @endslot
        @slot('title')
            Billing Details
        @endslot
    @endcomponent

    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h5 class="card-title flex-grow-1 mb-0">Billing Details</h5>
                    <div class="flex-shrink-0">
                        @if($billing->status !== 'paid')
                            <a href="{{ route('admin.tenant-billings.mark-paid', $billing) }}" class="btn btn-success btn-sm">
                                <i class="ri-check-line align-bottom me-1"></i> Mark as Paid
                            </a>
                        @endif
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-borderless mb-0">
                            <tbody>
                                <tr>
                                    <td class="fw-medium" style="width: 180px;">Tenant</td>
                                    <td>{{ $billing->tenant->name }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-medium">Billing Period</td>
                                    <td>{{ $billing->billing_period }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-medium">Amount</td>
                                    <td class="fs-5 fw-bold">Rp {{ number_format($billing->amount, 0, ',', '.') }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-medium">Due Date</td>
                                    <td>{{ $billing->due_date->format('d M Y') }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-medium">Status</td>
                                    <td>
                                        <span class="badge bg-{{ $billing->status === 'paid' ? 'success' : ($billing->status === 'overdue' ? 'danger' : 'warning') }}">
                                            {{ ucfirst($billing->status) }}
                                        </span>
                                    </td>
                                </tr>
                                @if($billing->paid_at)
                                <tr>
                                    <td class="fw-medium">Paid At</td>
                                    <td>{{ $billing->paid_at->format('d M Y H:i') }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-medium">Paid Amount</td>
                                    <td>Rp {{ number_format($billing->paid_amount, 0, ',', '.') }}</td>
                                </tr>
                                @endif
                                @if($billing->notes)
                                <tr>
                                    <td class="fw-medium">Notes</td>
                                    <td>{{ $billing->notes }}</td>
                                </tr>
                                @endif
                                <tr>
                                    <td class="fw-medium">Generated By</td>
                                    <td>{{ $billing->generator->name ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <td class="fw-medium">Created At</td>
                                    <td>{{ $billing->created_at->format('d M Y H:i') }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
